name: Run Shell Commands
on: [push]

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps:
      - name: Echo a String
        run: echo "Hello Security Gurus!! This is our first GitHub Actions Workflow file"

